apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-petstore-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: pipelines
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-camel/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: pipelines
        component: petstore
        environment: dev
        image:
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: pipelines-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m